name: hi-file-parser
version: 0.1.3.0
github: commercialhaskell/hi-file-parser
license: BSD3
author: Hussein Ait-Lahcen
maintainer: michael@snoyman.com

extra-source-files:
- README.md
- ChangeLog.md
- test-files/iface/x32/ghc7103/Main.hi
- test-files/iface/x32/ghc8002/Main.hi
- test-files/iface/x32/ghc8022/Main.hi
- test-files/iface/x32/ghc8044/Main.hi
- test-files/iface/x64/ghc8022/Main.hi
- test-files/iface/x64/ghc8022/X.hi
- test-files/iface/x64/ghc8044/Main.hi
- test-files/iface/x64/ghc8044/X.hi
- test-files/iface/x64/ghc8064/Main.hi
- test-files/iface/x64/ghc8064/X.hi
- test-files/iface/x64/ghc8084/Main.hi
- test-files/iface/x64/ghc8084/X.hi
- test-files/iface/x64/ghc8104/Main.hi
- test-files/iface/x64/ghc8104/X.hi
- test-files/iface/x64/ghc9001/Main.hi
- test-files/iface/x64/ghc9001/X.hi
- test-files/iface/x64/ghc9027/Main.hi
- test-files/iface/x64/ghc9027/X.hi
- test-files/iface/x64/ghc9044/Main.hi
- test-files/iface/x64/ghc9044/X.hi
- test-files/iface/x64/ghc9045/Main.hi
- test-files/iface/x64/ghc9045/X.hi
- test-files/iface/x64/ghc9061/Main.hi
- test-files/iface/x64/ghc9061/X.hi

# Metadata used when publishing your package
synopsis: Parser for GHC's hi files
category: Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/commercialhaskell/hi-file-parser/blob/master/README.md>

dependencies:
- base >= 4.10 && < 5
- binary
- bytestring
- rio
- vector
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  hi-file-parser-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hi-file-parser
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
