spec-version: 0.36.0

name: hi-file-parser
version: 0.1.8.0
github: commercialhaskell/hi-file-parser
synopsis: Parser for GHC's *.hi files
description: |
  A parser for GHC's *.hi files. Extracts information about dependencies and
  usage of files.
category: Development
author: Hussein Ait-Lahcen <hussein.aitlahcen@gmail.com>
maintainer:
- Michael Snoyman <michael@snoyman.com>
- Mike Pilgrem <public@pilgrem.com>
copyright: Copyright 2015-2025, Stack contributors

extra-source-files:
- README.md
- ChangeLog.md
- test-files/iface/x32/ghc7103/Main.hi
- test-files/iface/x32/ghc8002/Main.hi
- test-files/iface/x32/ghc8022/Main.hi
- test-files/iface/x32/ghc8044/Main.hi
- test-files/iface/x64/ghc8022/Main.hi
- test-files/iface/x64/ghc8022/X.hi
- test-files/iface/x64/ghc8044/Main.hi
- test-files/iface/x64/ghc8044/X.hi
- test-files/iface/x64/ghc8065/Main.hi
- test-files/iface/x64/ghc8065/X.hi
- test-files/iface/x64/ghc8084/Main.hi
- test-files/iface/x64/ghc8084/X.hi
- test-files/iface/x64/ghc8107/Main.hi
- test-files/iface/x64/ghc8107/X.hi
- test-files/iface/x64/ghc9002/Main.hi
- test-files/iface/x64/ghc9002/X.hi
- test-files/iface/x64/ghc9028/Main.hi
- test-files/iface/x64/ghc9028/X.hi
- test-files/iface/x64/ghc9044/Main.hi
- test-files/iface/x64/ghc9044/X.hi
- test-files/iface/x64/ghc9048/Main.hi
- test-files/iface/x64/ghc9048/X.hi
- test-files/iface/x64/ghc9067/Main.hi
- test-files/iface/x64/ghc9067/X.hi
- test-files/iface/x64/ghc9084/Main.hi
- test-files/iface/x64/ghc9084/X.hi
- test-files/iface/x64/ghc9102/Main.hi
- test-files/iface/x64/ghc9102/X.hi
- test-files/iface/x64/ghc9122/Main.hi
- test-files/iface/x64/ghc9122/X.hi
- test-files/iface/x64/ghc9140/Main.hi
- test-files/iface/x64/ghc9140/X.hi

dependencies:
- base >= 4.10 && < 5
- binary
- bytestring
- rio
- vector
- mtl
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  hi-file-parser-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hi-file-parser
    - hspec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
