name: Linting

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  style:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Clone project
      uses: actions/checkout@v3
    - name: Apply yamllint
      uses: ibiqlik/action-yamllint@v3
      with:
        format: github
    - name: Set up HLint
      uses: haskell/actions/hlint-setup@v2
      with:
        version: "3.4"
    - name: Apply HLint
      uses: haskell/actions/hlint-run@v2
      with:
        path: src/
        fail-on: warning
