name: Tests

on:
  pull_request:
  push:
    branches:
    - master
  workflow_dispatch:

# As of 2025-08-30, ubuntu-latest and windows-latest come with Stack 3.7.1.
# macos-13 and macos-latest do not come with Haskell tools.

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-13 # x86_64
        - macos-latest # AArch64
        snapshot:
        - stack-ghc-8.10.7.yaml
        - stack-ghc-9.0.2.yaml
        - stack-ghc-9.2.8.yaml
        - stack-ghc-9.4.8.yaml
        - stack-ghc-9.6.7.yaml
        - stack-ghc-9.8.4.yaml
        - stack-ghc-9.10.2.yaml
        - stack-ghc-9.12.2.yaml
        exclude:
        - os: macos-latest
          snapshot: stack-ghc-8.10.7.yaml # GHC 8.10.7 needs LLVM >= 9 & <= 12
        - os: macos-latest
          snapshot: stack-ghc-9.0.2.yaml # GHC 9.0.2 needs LLVM >= 9 & <= 12
    steps:
    - name: Clone project
      uses: actions/checkout@v4
    - name: Cache dependencies on Unix-like OS
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      uses: actions/cache@v4
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles( matrix.resolver ) }}
    - name: Cache dependencies on Windows
      if: startsWith(runner.os, 'Windows')
      uses: actions/cache@v4
      with:
        path: |
          ~\AppData\Roaming\stack
          ~\AppData\Local\Programs\stack
        key: ${{ runner.os }}-${{ hashFiles( matrix.resolver ) }}
    - name: Install dependencies and test
      shell: bash
      run: |
        set -ex
        if [[ "${{ matrix.os }}" == "macos-13" || "${{ matrix.os }}" == "macos-latest" ]]
        then
          # macos-13 and macos-latest do not include Haskell tools as at 2025-08-30.
          curl -sSL https://get.haskellstack.org/ | sh
        fi
        stack --snapshot=${{ matrix.snapshot }} test --bench --only-dependencies
        stack --snapshot=${{ matrix.snapshot }} test --haddock --no-haddock-deps --bench --no-run-benchmarks
