name: Tests

on:
  pull_request:
  push:
    branches:
    - master
  workflow_dispatch:

# As of 2026-06-12:
# * ubuntu-latest comes with Stack 3.9.3 and GHC 9.14.1; and
# * windows-latest comes with Stack 3.9.3 and GHC 9.14.1.
# However, macos-15-intel and macos-latest do not come with Haskell tools.

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        # macos-15-intel will be the last that provides macOS/x86_64
        - macos-15-intel # x86_64
        - macos-latest # AArch64
        snapshot:
        - stack-ghc-9.2.8.yaml
        - stack-ghc-9.4.8.yaml
        - stack-ghc-9.6.7.yaml
        - stack-ghc-9.8.4.yaml
        - stack-ghc-9.10.3.yaml
        - stack-ghc-9.12.4.yaml
        - stack-ghc-9.14.1.yaml
    steps:
    - name: Clone project
      uses: actions/checkout@v7
    - name: Cache dependencies on Unix-like OS
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      uses: actions/cache@v6
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles( matrix.snapshot ) }}
    - name: Cache dependencies on Windows
      if: startsWith(runner.os, 'Windows')
      uses: actions/cache@v6
      with:
        path: |
          ~\AppData\Roaming\stack
          ~\AppData\Local\Programs\stack
        key: ${{ runner.os }}-${{ hashFiles( matrix.snapshot ) }}
    - name: Install dependencies and test
      shell: bash
      run: |
        set -ex
        if [[ "${{ matrix.os }}" == "macos-15-intel" || "${{ matrix.os }}" == "macos-latest" ]]
        then
          # macos-15-intel and macos-latest do not include Haskell tools as at
          # 2026-06-12.
          curl -sSL https://get.haskellstack.org/ | sh
        fi
        stack --snapshot=${{ matrix.snapshot }} test --bench --only-dependencies
        stack --snapshot=${{ matrix.snapshot }} test --haddock --no-haddock-deps --bench --no-run-benchmarks
